Dz1
Eldaen/react_dz pull request #2
Opened 2017-12-07 17:07 UTC by Eldaen

2017-12-07 17:52 UTC, ubcent approved these changes

2017-12-07 17:53 UTC, ubcent requested changes
Нужно поправить оформление и проверить метод removeDev в классе Manager

2017-12-07 17:57 UTC, ubcent commented
```javascript
const devs = [
  new Dev(..),
  new Dev(...)
];

const man = new Man(devs.reduce((acc, item) => Object.assign({}, { [item.id]: item }), {})
```

2017-12-08 14:26 UTC, Eldaen commented
Сделал рефакторинг и исправление ошибок.

2017-12-08 14:28 UTC, ubcent approved these changes
Looks better 🆒

2017-12-08 14:44 UTC, merged